In [2]:
counter = 0
print(counter)
while counter < 4:
    print(counter)
    counter +=1

print("Final counter", counter)

0
0
1
2
3
Final counter 4


In [3]:
for counter in range(4):
    print(counter)

0
1
2
3


In [8]:
fruits = ["bannana", "mango", "pineapple"]
only_index ={}
for index, f in enumerate(fruits):
    only_index[index] = f
    print(only_index)

print(f"final output {only_index}")

{0: 'bannana'}
{0: 'bannana', 1: 'mango'}
{0: 'bannana', 1: 'mango', 2: 'pineapple'}
final output {0: 'bannana', 1: 'mango', 2: 'pineapple'}


In [17]:
new_list = []

for i in range(10):
    new_list.append(i *10)

print(new_list)

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]


In [19]:
new_list = [i *10 for i in range(10)]
print(new_list)

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]


In [27]:
def example(ss:str)-> str:
    if isinstance(ss, str):
        return ss.lower()


example1 = example("hey")
print(example1)
example2 = example(2)
print(example2)

hey
None


In [30]:
def iter_func(a, b):
    for i in range(a):
        yield i*b

for i in iter_func(10, 2):
    print(i + 5)

5
7
9
11
13
15
17
19
21
23


In [34]:
class myclass():
    id:str = "hello"

p = myclass()
print(p.id)

hello


In [35]:
class Person:
    x = 5
    def __init__(self, name, age):
        self.name = name
        self.age = age
        counter = 1
        self.x += 1 

p1 = Person("John", 36)

print(p1.name)
print(p1.age)
print(p1.x)
print(p1.counter)

John
36
6


AttributeError: 'Person' object has no attribute 'counter'

In [36]:
#Very basic Mark keeping class
class Marks:
    max_mark = 90
    def __init__(self, num_students, raw_marks):
        self.number_of_students = num_students
        self.raw_students_marks = raw_marks
        
        #raise will give a warning and tell Python to stop running the code
        if len(self.raw_students_marks) != self.number_of_students:
            raise ValueError("The number of students defined does not equal the numer of marks given")
        
    def __len__(self):
        return self.number_of_students
    
    def __iter__(self):
        #return a generator object that will calculate the percentage for each mark
        return ((mark / self.max_mark) * 100 for mark in self.raw_students_marks)

marks = Marks(6, [50, 32, 61, 75, 83, 32])

#Using len() on our class will return the ouput from the __len__ method
print("Number of students", len(marks))

#We can simply iterate over our class as we have defined an __iter__ method
for i, mark in enumerate(marks):
    print("Student %d mark percentage %.2f" %(i, mark))

Number of students 6
Student 0 mark percentage 55.56
Student 1 mark percentage 35.56
Student 2 mark percentage 67.78
Student 3 mark percentage 83.33
Student 4 mark percentage 92.22
Student 5 mark percentage 35.56


In [38]:
x = [1, 2, 3, 4, 5]

for i in range(len(x)):
    print(x[i])

1
2
3
4
5


In [40]:
W = [[1, 1, 1],
     [1.5, 1.5, 1.5],
     [2, 2, 2]]

#3x1
x = [[6], [7], [8]]
#3x1
b = [[1], [1], [1]]

#Variable to store output
#3x1
y = [[0], [0], [0]]

In [41]:
import numpy as np

#We can transform our list of lists into a "numpy array" by using the function "array"
W_np = np.array(W)

x_np = np.array(x)

#lets use the function "ones" to create an array of ones!
b_np = np.ones((3, 1))

#Lets now compute Wx + b using these numpy variables!
output = np.matmul(W_np, x_np) + b_np

#print out the result
print("Output:\n", output)
print("Output shape:\n", output.shape)

Output:
 [[22. ]
 [32.5]
 [43. ]]
Output shape:
 (3, 1)


In [42]:
T = np.random.random((2, 3, 4))
print("Our 3D Tensor:\n", T)

Our 3D Tensor:
 [[[0.99306891 0.38098543 0.04776829 0.60861294]
  [0.44467089 0.91621151 0.94057535 0.55817396]
  [0.18033412 0.05544085 0.24962609 0.48049783]]

 [[0.61813872 0.79828365 0.27876223 0.54025992]
  [0.05774377 0.07839759 0.77377194 0.58368827]
  [0.16647814 0.88700231 0.54763756 0.89057505]]]
