In [1]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

# The Pytorch Tensor

As we've already explored the "Tensor" is a useful concept and is very useful in Machine Learning, however you probably noticed in Numpy that our "Tensors" are called "Arrays", but now we are in Pytorch this is no more!!
Let's do a recap of Numpy arrays and how similar they are to Pytorch tensors.

In [2]:
# Create some "Matrices" as lists of lists  

# 3x3
W = [[1, 1, 1],
     [1.5, 1.5, 1.5],
     [2, 2, 2]]

# 3x1
x = [[6], [7], [8]]
# 3x1
b = [[1], [1], [1]]

# Variable to store output
# 3x1
y = [[0], [0], [0]]

In [3]:
# We can transform our list of lists into a "numpy array" by using the function "array"
W_np = np.array(W)

x_np = np.array(x)

# Lets use the function "ones" to create an array of ones!
b_np = np.ones((3, 1))

# Lets now compute Wx + b using these numpy variables!
output = np.matmul(W_np, x_np) + b_np

# Print out the result
print("Output:\n", output)
print("Output shape:\n", output.shape)

Output:
 [[22. ]
 [32.5]
 [43. ]]
Output shape:
 (3, 1)


Now in Pytorch!

In [4]:
# We can transform our list of lists into a "torch tensor" by using the function "FloatTensor"
# Note: here we've specified the datatype of the tensor, a 32bit "float" you can also just use the function "tensor"
# But this will inherit the datatype of the array given, to ensure the data-types are the same
# (and we can perform the wanted operations) we use "FloatTensor"

W_torch = torch.FloatTensor(W)

x_torch = torch.FloatTensor(x)

# Lets use the function "ones" to create an array of ones!
b_torch = torch.ones(3, 1)

# Lets now compute Wx + b using these numpy variables!
output = torch.matmul(W_torch, x_torch) + b_torch

# Print out the result
print("Output:\n", output)
print("Output shape:\n", output.shape)

Output:
 tensor([[22.0000],
        [32.5000],
        [43.0000]])
Output shape:
 torch.Size([3, 1])


In [5]:
# Create a random Numpy array
np_array = np.random.random((3, 4))
print("Numpy array:\n", np_array)

# Convert to Pytorch tensor
torch_tensor = torch.FloatTensor(np_array)
print("Pytorch tensor:\n", torch_tensor)

# Convert back to a Numpy array!
np_array2 = torch_tensor.numpy()
print("Numpy array:\n", np_array2)

Numpy array:
 [[0.76640817 0.85541004 0.25723197 0.37059769]
 [0.93366588 0.2866114  0.50014405 0.76312133]
 [0.69533851 0.0326273  0.53710684 0.90561869]]
Pytorch tensor:
 tensor([[0.7664, 0.8554, 0.2572, 0.3706],
        [0.9337, 0.2866, 0.5001, 0.7631],
        [0.6953, 0.0326, 0.5371, 0.9056]])
Numpy array:
 [[0.76640815 0.85541004 0.25723195 0.3705977 ]
 [0.9336659  0.2866114  0.50014406 0.7631213 ]
 [0.6953385  0.0326273  0.5371068  0.90561867]]


# On to Pytorch!

### Basic Element-wise Operations

In [6]:
# Lets create a 2D Tensor using torch.rand
y = torch.rand(4, 5)
# This will create a "Vector" of numbers from 0 to 1
print("Our 1D Tensor:\n",y)

# We can perform normal python scalar arithmetic on Torch tensors
print("\nScalar Multiplication:\n",y * 10)
print("Addition and Square:\n",(y + 1)**2)
print("Addition:\n",y + y)
print("Addition and division:\n",y / (y + 1))

# We can use a combination of Torch functions and normal python arithmetic
print("\nPower and square root:\n",torch.sqrt(y**2))

# Torch tensors are objects and have functions
print("\nY -\n Min:%.2f\n Max:%.2f\n Standard Deviation:%.2f\n Sum:%.2f" %(y.min(), y.max(), y.std(), y.sum()))

Our 1D Tensor:
 tensor([[0.7144, 0.0079, 0.4662, 0.6847, 0.7110],
        [0.2405, 0.7468, 0.2264, 0.2958, 0.1670],
        [0.5946, 0.0902, 0.6495, 0.4313, 0.4967],
        [0.5198, 0.9067, 0.0469, 0.0406, 0.6376]])

Scalar Multiplication:
 tensor([[7.1437, 0.0788, 4.6621, 6.8474, 7.1096],
        [2.4051, 7.4676, 2.2636, 2.9585, 1.6698],
        [5.9455, 0.9019, 6.4953, 4.3131, 4.9674],
        [5.1977, 9.0670, 0.4686, 0.4059, 6.3755]])
Addition and Square:
 tensor([[2.9391, 1.0158, 2.1498, 2.8383, 2.9274],
        [1.5389, 3.0512, 1.5040, 1.6792, 1.3618],
        [2.5426, 1.1885, 2.7210, 2.0487, 2.2402],
        [2.3097, 3.6355, 1.0959, 1.0828, 2.6816]])
Addition:
 tensor([[1.4287, 0.0158, 0.9324, 1.3695, 1.4219],
        [0.4810, 1.4935, 0.4527, 0.5917, 0.3340],
        [1.1891, 0.1804, 1.2991, 0.8626, 0.9935],
        [1.0395, 1.8134, 0.0937, 0.0812, 1.2751]])
Addition and division:
 tensor([[0.4167, 0.0078, 0.3180, 0.4064, 0.4155],
        [0.1939, 0.4275, 0.1846, 0.2283, 0.1431]

### Tensor Opperations

In [7]:
# Create two 3D Tensors
tensor_1 = torch.rand(3,3,3)
tensor_2 = torch.rand(3,3,3)

# Add the 2 Tensors
print("Addition:\n",tensor_1 + tensor_2)

# We cannot perform a normal "matrix" multiplication on a 3D tensor
# But we can treat the 3D tensor as a "batch" (like a stack) of 2D tensors
# And perform normal matrix multiplication independantly on each pair of 2D matricies
print("Batch Multiplication:\n", torch.bmm(tensor_1, tensor_2))

Addition:
 tensor([[[0.7146, 1.0001, 1.5261],
         [1.0963, 1.3729, 0.9445],
         [0.9579, 1.3622, 1.3227]],

        [[0.7653, 0.6280, 1.2156],
         [0.6094, 1.4813, 1.3763],
         [1.6987, 1.5045, 0.9818]],

        [[1.0300, 1.2584, 0.8388],
         [1.0492, 0.8732, 1.2040],
         [1.1455, 1.4250, 0.5757]]])
Batch Multiplication:
 tensor([[[0.5627, 0.9781, 1.1698],
         [0.9427, 1.1173, 1.0332],
         [0.7177, 1.0688, 1.1963]],

        [[0.8565, 0.8164, 0.2214],
         [1.1380, 1.3651, 0.5242],
         [1.3180, 1.5556, 0.6958]],

        [[1.2960, 1.5717, 1.1901],
         [0.3709, 0.4188, 0.2047],
         [0.8509, 0.7871, 0.5801]]])


In [8]:
# Lets create a more interesting tensor
tensor_3 = torch.rand(2,4,5)
# We can swap the Tensor dimensions
print("\nThe origional Tensor is is:\n", tensor_3)
print("With shape:\n", tensor_3.shape)

# Tranpose will swap the dimensions it is given
print("The Re-arranged is:\n", tensor_3.transpose(0,2))
print("With shape:\n", tensor_3.transpose(0,2).shape)


The origional Tensor is is:
 tensor([[[0.5117, 0.3487, 0.5408, 0.5091, 0.1264],
         [0.2356, 0.1533, 0.6542, 0.8206, 0.2142],
         [0.8137, 0.4350, 0.5843, 0.9452, 0.2746],
         [0.5138, 0.5669, 0.4630, 0.7579, 0.1719]],

        [[0.3228, 0.3491, 0.3305, 0.8338, 0.4240],
         [0.9159, 0.3092, 0.3467, 0.8309, 0.6767],
         [0.9993, 0.8506, 0.4354, 0.1816, 0.2539],
         [0.8753, 0.2304, 0.0096, 0.5243, 0.2517]]])
With shape:
 torch.Size([2, 4, 5])
The Re-arranged is:
 tensor([[[0.5117, 0.3228],
         [0.2356, 0.9159],
         [0.8137, 0.9993],
         [0.5138, 0.8753]],

        [[0.3487, 0.3491],
         [0.1533, 0.3092],
         [0.4350, 0.8506],
         [0.5669, 0.2304]],

        [[0.5408, 0.3305],
         [0.6542, 0.3467],
         [0.5843, 0.4354],
         [0.4630, 0.0096]],

        [[0.5091, 0.8338],
         [0.8206, 0.8309],
         [0.9452, 0.1816],
         [0.7579, 0.5243]],

        [[0.1264, 0.4240],
         [0.2142, 0.6767],
        

In [9]:
# Lets create a 2D Tensor
tensor = torch.rand(3, 2)

# View the Number of elements in every dimension
print("The Tensors shape is:", tensor.shape)

# Unsqueeze adds an "empty" dimension to our Tensor
print("Add an empty dimenson to dim3:", tensor.unsqueeze(2).shape)

# Unsqueeze adds an "empty" dimension to our Tensor
print("Add an empty dimenson to dim2:", tensor.unsqueeze(1).shape)

The Tensors shape is: torch.Size([3, 2])
Add an empty dimenson to dim3: torch.Size([3, 2, 1])
Add an empty dimenson to dim2: torch.Size([3, 1, 2])


In [10]:
# Lets create a 4D Tensor with a few "empty" dimensions
tensor = torch.rand(1, 3, 1, 2)

# view the Number of elements in every dimension
print("The Tensors shape is:", tensor.shape)

# squeeze removes an "empty" dimension from our Tensor
print("Remove empty dimenson dim3:", tensor.squeeze(2).shape)

# squeeze removes an "empty" dimension from our Tensor
print("Remove empty dimenson dim0:", tensor.squeeze(0).shape)

# If we don't specify a dimension, squeeze will remove ALL empty dimensions
print("Remove all empty dimensons:", tensor.squeeze().shape)

The Tensors shape is: torch.Size([1, 3, 1, 2])
Remove empty dimenson dim3: torch.Size([1, 3, 2])
Remove empty dimenson dim0: torch.Size([3, 1, 2])
Remove all empty dimensons: torch.Size([3, 2])


In [11]:
# Lets create 2 differently shaped 4D Tensors (Matrices)
tensor1 = torch.rand(1, 4, 3, 1)
tensor2 = torch.rand(3, 4, 1, 4)

print("Tensor 1 shape:\n", tensor1.shape)
print("Tensor 2 shape:\n", tensor2.shape)

tensor3 = tensor1 + tensor2

print("The resulting shape is:\n", tensor3.shape)

Tensor 1 shape:
 torch.Size([1, 4, 3, 1])
Tensor 2 shape:
 torch.Size([3, 4, 1, 4])
The resulting shape is:
 torch.Size([3, 4, 3, 4])
